[custom]
enable_rule_generator=true
overwrite_original_rules=true

; ===================== 基础设置 =====================
custom_proxy_group=节点选择`select`[]🇹🇼 台湾自动`[]🇯🇵 日本自动`[]🇺🇸 美国自动`[]🇸🇬 狮城自动`[]🎃 低倍率自动`.*
; ===================== 业务分流组 =====================
custom_proxy_group=谷歌服务`select`[]节点选择`[]🇯� 日本自动`[]🇸🇬 狮城自动`[]�� 台湾自动`[]🇺🇸 美国自动`[]� 低倍率自动`[]全局直连`.*
custom_proxy_group=流媒体`select`[]节点选择`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]🎃 低倍率自动`[]全局直连`.*
custom_proxy_group=社交媒体`select`[]节点选择`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]� 低倍率自动`[]全局直连`.*
custom_proxy_group=AI`select`[]节点选择`[]🇯� 日本自动`[]🇸🇬 狮城自动`[]�� 台湾自动`[]🇺🇸 美国自动`[]� 低倍率自动`[]全局直连`.*
custom_proxy_group=微软服务`select`[]节点选择`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]🎃 低倍率自动`[]全局直连`.*
custom_proxy_group=苹果服务`select`[]节点选择`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]� 低倍率自动`[]全局直连`.*
custom_proxy_group=动画疯`select`[]节点选择`[]�🇵 日本自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]🎃 低倍率自动`[]全局直连`.*
custom_proxy_group=Spotify`select`[]节点选择`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]🎃 低倍率自动`[]全局直连`.*
custom_proxy_group=Steam&Game`select`[]节点选择`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]🎃 低倍率自动`[]全局直连`.*
custom_proxy_group=广告过滤`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=全局直连`select`[]DIRECT`[]节点选择`.*
custom_proxy_group=漏网之鱼`select`[]节点选择`[]🇯🇵 日本自动`[]🇸🇬 狮城自动`[]🇹🇼 台湾自动`[]🇺🇸 美国自动`[]🎃 低倍率自动`[]全局直连`.*
custom_proxy_group=🇹� 台湾自动`url-test`(?i)台湾|日月潭|tw|taiwan`http://www.gstatic.com/generate_204`300`40
custom_proxy_group=�🇯🇵 日本自动`url-test`(?i)日本|Japan|JP|JAPAN|🇯🇵`http://www.gstatic.com/generate_204`300`40
custom_proxy_group=🇺🇸 美国自动`url-test`(?i)美国|us|america|🇺🇸`http://www.gstatic.com/generate_204`300`40
custom_proxy_group=🇸🇬 狮城自动`url-test`(?i)新加坡|狮城|sg|singapore|🇸🇬`http://www.gstatic.com/generate_204`300`40
custom_proxy_group=🎃 低倍率自动`url-test`[⁰¹²³⁴⁵⁶⁷⁸⁹˙.]+ˣ`http://www.gstatic.com/generate_204`300`40

; ===================== 规则集引用 =====================
; 自定义细化规则
ruleset=AI,[]DOMAIN,trae-api-sg.mchost.guru
ruleset=AI,[]DOMAIN-SUFFIX,trae.ai
ruleset=全局直连,[]IP-CIDR,152.69.184.104/32,no-resolve
ruleset=谷歌服务,[]DOMAIN,redirector.c.play.google.com
ruleset=谷歌服务,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=谷歌服务,[]DOMAIN-SUFFIX,googleapis.cn
ruleset=谷歌服务,[]DOMAIN,services.googleapis.cn
ruleset=谷歌服务,[]DOMAIN,play.googleapis.com
ruleset=谷歌服务,[]DOMAIN,play-fe.googleapis.com
ruleset=谷歌服务,[]DOMAIN,android.clients.google.com
ruleset=谷歌服务,[]DOMAIN,play-lh.googleusercontent.com
ruleset=谷歌服务,[]DOMAIN,mtalk.google.com
ruleset=谷歌服务,[]DOMAIN-SUFFIX,gstatic.com
ruleset=谷歌服务,[]DOMAIN-SUFFIX,googlevideo.com
ruleset=谷歌服务,[]DOMAIN-SUFFIX,ytimg.com
ruleset=谷歌服务,[]DOMAIN-SUFFIX,ggpht.com
ruleset=谷歌服务,[]DOMAIN-SUFFIX,gvt1.com
ruleset=谷歌服务,[]DOMAIN-SUFFIX,gvt2.com
ruleset=谷歌服务,[]DOMAIN-SUFFIX,gvt3.com
ruleset=节点选择,[]DOMAIN-SUFFIX,github.io
ruleset=节点选择,[]DOMAIN,v2rayse.com
ruleset=全局直连,[]DOMAIN-SUFFIX,invite.linuxdo.org
ruleset=Steam&Game,[]PROCESS-NAME,java.exe
ruleset=Steam&Game,[]PROCESS-NAME,javaw.exe
ruleset=Steam&Game,[]PROCESS-NAME,GTA5.exe
ruleset=Steam&Game,[]PROCESS-NAME,PlayGTAV.exe
ruleset=Steam&Game,[]PROCESS-NAME,SocialClubHelper.exe
ruleset=Steam&Game,[]PROCESS-NAME,RiotClientServices.exe
ruleset=Steam&Game,[]PROCESS-NAME,LeagueClientUx.exe
ruleset=Steam&Game,[]PROCESS-NAME,VALORANT-Win64-Shipping.exe
ruleset=Steam&Game,[]PROCESS-NAME,FortniteClient-Win64-Shipping.exe
ruleset=Steam&Game,[]PROCESS-NAME,cs2.exe
ruleset=Steam&Game,[]PROCESS-NAME,dota2.exe
ruleset=Steam&Game,[]PROCESS-NAME,Battle.net.exe
ruleset=Steam&Game,[]PROCESS-NAME,Wow.exe
ruleset=Steam&Game,[]PROCESS-NAME,Diablo IV.exe
ruleset=Steam&Game,[]PROCESS-NAME,PathOfExile.exe
ruleset=Steam&Game,[]PROCESS-NAME,PathOfExileSteam.exe

; 业务规则
ruleset=广告过滤,[]GEOSITE,category-ads-all
ruleset=苹果服务,[]GEOSITE,apple
ruleset=微软服务,[]GEOSITE,microsoft
ruleset=流媒体,[]GEOSITE,youtube
ruleset=流媒体,[]GEOSITE,netflix
ruleset=流媒体,[]GEOSITE,tiktok
ruleset=动画疯,https://fastly.jsdelivr.net/gh/xiaolin-007/clash@main/rule/Bahamut.txt
ruleset=动画疯,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/BiliBiliIntl/BiliBiliIntl.list
ruleset=Spotify,[]GEOSITE,spotify
ruleset=Steam&Game,[]GEOSITE,steam
ruleset=Steam&Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=Steam&Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=Steam&Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=Steam&Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
ruleset=Steam&Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list
ruleset=Steam&Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=Steam&Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=AI,[]GEOSITE,openai
ruleset=社交媒体,[]GEOSITE,twitter
ruleset=社交媒体,[]GEOSITE,telegram
ruleset=社交媒体,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
ruleset=谷歌服务,[]GEOSITE,google

; 通用代理与直连规则
ruleset=节点选择,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
ruleset=节点选择,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
ruleset=节点选择,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
ruleset=全局直连,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
ruleset=全局直连,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
ruleset=全局直连,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
ruleset=全局直连,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
ruleset=全局直连,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
ruleset=全局直连,[]GEOIP,lan,no-resolve
ruleset=全局直连,[]GEOIP,cn,no-resolve
ruleset=漏网之鱼,[]FINAL

; ===================== 排除项 =====================
exclude_remarks=(?i)官网|套餐|流量|异常|剩余|到期|港|hk|HK|Hong|HONG|九龙
